-- ============================================================================
--  locality  — cities, towns, suburbs. Formerly `city`.
-- ============================================================================
--  Not an ISO standard, hence no iso_ prefix. "Locality" is the official
--  Australian term (G-NAF, Australia Post) for what is colloquially a suburb.

-- DROP TABLE IF EXISTS public.locality;

CREATE TABLE public.locality (
    id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code     text    NOT NULL,
    subdivision_code text    NOT NULL,
    locality_code    text    NOT NULL,
    name             text    NOT NULL,
    locality_type    text    NOT NULL DEFAULT 'suburb',
    status           text    NOT NULL DEFAULT 'active',
    notes            text    NOT NULL DEFAULT '',

    --  Composite FK: validates the pair together. ('AU','CA') is two
    --  individually-valid codes naming nothing. Country validity follows
    --  transitively via iso_subdivision, so no direct FK to iso_country.
    CONSTRAINT locality_subdivision_fkey
        FOREIGN KEY (country_code, subdivision_code)
        REFERENCES public.iso_subdivision (country_code, subdivision_code)
        ON UPDATE CASCADE,

    CONSTRAINT locality_code_key    UNIQUE (country_code, subdivision_code, locality_code),
    CONSTRAINT locality_code_check  CHECK (locality_code ~ '^[A-Z0-9]{1,5}$'),
    CONSTRAINT locality_name_check  CHECK (char_length(name) BETWEEN 1 AND 128),
    CONSTRAINT locality_status_check
        CHECK (status IN ('active', 'inactive')),
    CONSTRAINT locality_type_check  CHECK (locality_type IN
        ('city', 'county', 'parish', 'town', 'suburb', 'village',
         'locality', 'municipality'))
);

--  Deliberately NOT unique on name: locality names genuinely repeat within a
--  single subdivision. A unique constraint here rejects valid gazetteer data.
CREATE INDEX locality_name_idx ON public.locality (country_code, lower(name));

--  UN/LOCODE. Enable ONLY if locality_code holds the 3-character location part
--  ('MEL'), not the full 5-character code ('AUMEL') — otherwise this
--  yields 'AUAUMEL'. Verify first with the query in OPEN QUESTIONS below.
--
-- ALTER TABLE public.locality
--     ADD COLUMN unlocode text
--     GENERATED ALWAYS AS (country_code || locality_code) STORED;
-- CREATE UNIQUE INDEX locality_unlocode_key ON public.locality (unlocode);

COMMENT ON TABLE public.locality IS
    'Cities, towns, suburbs and rural localities within an ISO subdivision.';


-- ============================================================================
